import figlet from 'figlet';
import chalk from 'chalk';

// Arte ASCII Definitivo (Tamaño Medio - "The M-Dog")
const DOG_ART = `
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0oOWMMMMMMMMMMMMMMMMMWOo0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,.dNMMMMMMMMMMMMMMMNd.;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo..lKMMMMMMMMMMMMMKl..dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc',:OWMMMMMMMMMNk:,'lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0ONMMMMWd'll,xWMMMMMMMWd,ll'dWMMMMNk0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;,OMMMWO'.dd.cNMMMMMMMXc.do.,OMMMMk';0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMKlccxWMM0, ,x:.cKNNNNNNNK:.:x, ;0MMWxcclXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWOOWMMMMMMMKldKdxWMK: .lo. .,,,,,,,,,. .ol. :XMWxdKooKMMMMMMMWOOWMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWo,dNMMMMM0ldNNdxWWd. .:;.              .;;. .xWWxdNXdlKMMMMMXd,dWMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMKc':OWMMNl;OX0loNWo.  ....            ....  .dWXooKXk;lNMMNO:'lKMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMNd..:ddl..'odolkW0;     .;l,       .,o;.     ;KWklodo'.'ldd:..dNMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMNOd,.        .oookoxO;  .';,:,.      .;:,;'.   :0xokloo.        .;dONMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMW0o,,'...       .',o0ocOc. .cxo'         'dxc. .cOco0l,..       ...,,;o0WMMMMMMMMMMMMMMMM
MMMMMMMMMMMMWO,. ..co,.         'c,,ol;. ....         .... .;ol,,:'         .;o:.. .;OMMMMMMMMMMMMMMMM
MMMMMMMMNKkdc'.    ...  .        .'. .;l.   .'.      .'.   .l;. .'.           ...    .'cdkKNMMMMMMMMMMM
MMMMWXOo;';loc'..';;'...;c'.          'x: .;kd.      .dx;. cx'        ...'c,...';;'..,col;':dOXWMMMMMMM
MMMWO:,..;OWNX0kkXWNKkocdXKl..        .dx;lKK:..''...:KKc;xd.        ..oKXdcdkKNWXkk0XWWO;.',:OWMMMMMM
MMMMK:..,kXX0O0XWMMWNXKOKWWk'.        .:dkKXO;.......:0XKkd:.        'kWW0OKXNWWMWX0O0XXk,..cKMMMMMMM
MMMMM0, .;okO0K0Okkkdo0NNWWk,.        .o:l0XN0o'  'coKNK0ccl.        .;kWWNNOodxxkO0K0Oko,. ;0MMMMMMMM
MMMMMWKdcllccooollll,.lO0KXNXk:.      ,l,lKNMNx'  'ckNMNKc,l,      .ckXNXK0Ol.,llllodoc:llcdKWMMMMMMMM
MMMMMMMMWKdoxdc;,,:coxkOO00KXNNk;.   .::.,dxo;';ll;'':oxd,.:;    .;ONNXK00OOkdoc;,,;ldxodKWMMMMMMMMMMM
MMMMMMMMMMN0Okkk0XWMMMMMMMMMWX000c. .;. ..',,;oxxlc;,,'.. .;. .c000XWMMMMMMMMMWX0kkkO0NMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkdo,....     .....''......      ...,odkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;..          .',,'..             ..;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXo.                                .oNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd;...            ....            ...;dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo;ll;'.         ......        .':ll;oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOoc:::;',,,'''...'.....'',,,,';:;:coONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKOl...   .:c;,,,,:c:;,,,,,:c:.   ..'lOKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk:...lkl;.   .;dd,..   .;lxc...:kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xll:'..   .,xx,..   .'':llxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOx0KOxdooloolooodxOK0xONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMWKKWMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
`;

export function showBanner() {
    console.clear();

    // 1. EL NOMBRE "CERBERUS"
    // Usamos rojo intenso (#FF4500) para el nombre y fuente Standard para máxima legibilidad
    console.log(
        chalk.hex('#FF4500')(
            figlet.textSync('CERBERUS', {
                font: 'Standard',
                horizontalLayout: 'default',
                verticalLayout: 'default',
            })
        )
    );

    // 2. EL ARTE (DIBUJO)
    // Usamos Blanco puro (#FFFFFF) para que el dibujo se vea nítido sobre fondo negro
    console.log(chalk.white(DOG_ART));

    // 3. DATOS DE ESTADO
    console.log(chalk.gray('===================================================================='));
    console.log(
        chalk.bold.white(' SYSTEM: ') + chalk.green('ONLINE 🟢') +
        chalk.gray(' | ') +
        chalk.bold.white('PORT: ') + chalk.yellow('3001') +
        chalk.gray(' | ') +
        chalk.bold.white('PROTOCOL: ') + chalk.cyan('3-DOGS')
    );
    console.log(chalk.gray('===================================================================='));
    console.log('\n');
}
